name: release test

on:
  workflow_dispatch:

permissions: read-all

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  release:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: |
          set -euo pipefail
          gh release -R laurentsimon/binaries download v0.0.0 -p policy-evaluator
          chmod o+x policy-evaluator
          image=docker.io/laurentsimon/slsa-project-echo-server@sha256:3ea35df97f1c8f80984322af66356fbf52d5c05baf7f41a0ec2fd6a5e75bc088
          ./policy-evaluator policies/release/org.json policies/release/ "${image}" creator_id dev